let data = {
  title: "photographe IRINA ADAMENKO",
  swiperIndex: [
    "img/swiperIndex/sw1.jpg",
    "img/swiperIndex/SWIP2.jpg",
    "img/swiperIndex/swipe22.jpg",
    "img/swiperIndex/swipe4.jpg",
    "img/swiperIndex/photo_2023-10-03_12-02-23.jpg"
  ],
  workStyle: [
    {
      name: "Famille",
      img: "/img/workStyle/Family.jpg",
      price: "250 €",
      form: "",
      info: [
        "Conseil et assistance à la création d'images pour le tournage",
        "1 heure de tournage",
        "En studio*, dans la nature ou à la maison",
        "Plus de 80 photos retouchées en HD",
        "Galerie privée en ligne pendant 7 jours Réservation d'un créneau par e-mail et versement d'un acompte de 30%.  Règlement du solde le jour de la séance ",
        "Les photos sont prêtes sous 2 semaines",
        "Si le tournage a lieu en studio, la location du studio est payée séparément (environ 60 € de l'heure).  ",
        "Si le lieu est en dehors de la ville, le coût du tournage augmente en tenant compte des frais de déplacement et de temps.",
      ]
    },
    {
      name: "Couple",
      img: "/img/workStyle/LoveS.jpg",
      price: "250 €",
      form: "",
      info: [
        "Conseil et assistance à la création d'images pour le tournage",
        "1 heure de tournage",
        "En studio*, dans la nature ou à la maison",
        "Plus de 80 photos retouchées en HD",
        "Galerie privée en ligne pendant 7 jours Réservation d'un créneau par e-mail et versement d'un acompte de 30%.  Règlement du solde le jour de la séance ",
        "Les photos sont prêtes sous 2 semaines",
        "Si le tournage a lieu en studio, la location du studio est payée séparément (environ 60 € de l'heure).  ",
        "Si le lieu est en dehors de la ville, le coût du tournage augmente en tenant compte des frais de déplacement et de temps.",
      ],
    },
    {
      name: "Grossesse",
      img: "/img/workStyle/beremennost.jpg",
      price: "250 €",
      form: "",
      info: [
        "Conseil et assistance à la création d'images pour le tournage",
        "1 heure de tournage",
        "En studio*, dans la nature ou à la maison",
        "Plus de 80 photos retouchées en HD",
        "Galerie privée en ligne pendant 7 jours Réservation d'un créneau par e-mail et versement d'un acompte de 30%.  Règlement du solde le jour de la séance ",
        "Les photos sont prêtes sous 2 semaines",
        "Si le tournage a lieu en studio, la location du studio est payée séparément (environ 60 € de l'heure).  ",
        "Si le lieu est en dehors de la ville, le coût du tournage augmente en tenant compte des frais de déplacement et de temps.",
      ]
    },
    {
      name: "Mariage",
      img: "/img/workStyle/wed3.jpg",
      price: "650 €",
      form: "MINIMUM",
      info: [
        "La durée de la séance est de 2 à 3 heures",
        "Conseil",
        "Traitement primaire, correction des couleurs de toutes les photos sélectionnées",
        "Retouche de portraits",
        "Une petite série de photographies en noir et blanc",
        "Le délai de livraison des photos peut aller jusqu'à 1 mois ﻿",
        "Photos de cérémonie, photos de groupes, photos de couple",
        " ﻿﻿150-200 photos (environ) retouchées ",
        " ﻿﻿Online galerie privée",
      ],
    },
    {
      name: "Mariage",
      img: "/img/workStyle/wedd.jpg",
      price: "1000 €",
      form: "STANDARD",
      info: [
        "Consultation (réunion)",
        "Photo de préparation avant le déjeuner (environ 6 à 8 heures de travail)",
        "Photos de groupe, photos de couple, photos de reportage cocktail, cérémonie",
        "Traitement primaire, correction des couleurs de toutes les photos sélectionnées",
        "Retouche de portraits",
        "Une petite série de photographies en noir et blanc",
        "Préparation de photos à hauteur de 400 à 600 photos retouchées dans un délai maximum de 2 mois",
        "Galerie privée en ligne.  ",
        "Transfert des photos terminées via échange de fichiers.",
      ],
    },
    {
      name: "Mariage",
      img: "/img/workStyle/Wedding.jpg",
      price: "1300 €",
      form: "MAXIMUM",
      info: [
        "Consultation (réunion)",
        "Photo de préparation avant le dîner(environ 9 à 10 heures de travail)",
        "Photos de groupe, photos de couple, photos de reportage cocktail, cérémonie, première danse, gâteau, jusqu'à 23h",
        "Traitement primaire, correction des couleurs de toutes les photos sélectionnées",
        "Retouche de portraits",
        "Une petite série de photographies en noir et blanc",
        "Préparation de photos à hauteur de 600 à 800 photos retouchées dans un délai maximum de 2 mois",
        "Galerie privée en ligne.  ",
        "Transfert des photos terminées via échange de fichiers.",
      ],
    },
  ],
  contact: [
    {
      url: "https://www.facebook.com/profile.php?id=100011367545612",
      icon: "/img/contact-icon/icons8-facebook-50.png",
    },
    {
      url: "https://instagram.com/adamenko_photography?igshid=NTc4MTIwNjQ2YQ==wa",
      icon: "/img/contact-icon/icons8-instagram-50.png",
    },
    {
      url: "https://t.me/AdamenkoIr",
      icon: "/img/contact-icon/icons8-логотип-telegram-50.png",
    },
  ],
  number: [
    {
      number: "",
    },
  ],
  email: "Adamenkosi@meta.ua",

  textAboutMe: {
    title: "Bonjour et bienvenue !",
    text: [
      "Je m'appelle Iryna et je suis photographe de famille. Je suis avocat de formation, mais je me suis lancée dans la photographie il y a 8 ans et depuis je ne peux pas imaginer ma vie sans appareil photo.",
      "Je suis ukrainienne, mais je vis avec ma famille à Lyon depuis près de deux ans. Je suis maman de trois enfants de 16, 10 et 3 ans, je m’entends donc bien avec les enfants de tous âges !",
      "J'aime photographier la vie telle qu'elle est. Avec moi, vous n'aurez pas à regarder timidement l’appareil photo, je vous guiderai en vous proposant des poses faciles, et tacherai à raconter votre historie. Des sourires sincères, des câlins, des jeux avec les enfants, les rituels quotidiens que vous appréciez - tous ces moments sont éphémères, alors il est important d’en garder le souvenir ! Ma mission est de conserver vos plus beaux souvenirs, vos heureux événements sous forme de belles photographies.",
    ],
    photo: "/img/photoAboutMe.jpg",
  },
  swiper: [
    {
      id: "1",
      category: "grossess",
      title: "Katya & Bogdan",
      mainImg: "/img/Album/Grossess/Katya&Bogdan/swipe3.jpg",
      img: [
        "/img/Album/Grossess/Katya&Bogdan/beremennost.jpg",
        "/img/Album/Grossess/Katya&Bogdan/grosss.jpg",
        "/img/Album/Grossess/Katya&Bogdan/photo_1_2023-09-19_12-17-27.jpg",
        "/img/Album/Grossess/Katya&Bogdan/photo_14_2023-09-19_12-17-27.jpg",
        "/img/Album/Grossess/Katya&Bogdan/photo_5_2023-09-19_12-17-27.jpg",
        "/img/Album/Grossess/Katya&Bogdan/photo_6_2023-09-19_12-17-27.jpg",
        "/img/Album/Grossess/Katya&Bogdan/photo_10_2023-09-19_12-17-27.jpg",
        "/img/Album/Grossess/Katya&Bogdan/photo_11_2023-09-19_12-17-27.jpg",
        "/img/Album/Grossess/Katya&Bogdan/photo_12_2023-09-19_12-17-27.jpg",
        "/img/Album/Grossess/Katya&Bogdan/photo_17_2023-09-19_12-17-27.jpg",
        "/img/Album/Grossess/Katya&Bogdan/SWIP.jpg",
        "/img/Album/Grossess/Katya&Bogdan/swipe3.jpg",
      ],
    },
    {
      id: "2",
      title: "Kristina & Andre",
      category: "love",
      mainImg: "/img/Album/LoveStory/Kristina & Andre/2.jpg",
      img: [
        "/img/Album/LoveStory/Kristina & Andre/1.jpg",
        "/img/Album/LoveStory/Kristina & Andre/2.jpg",
        "/img/Album/LoveStory/Kristina & Andre/LoveS.jpg",
        "/img/Album/LoveStory/Kristina & Andre/photo_2_2023-09-19_12-15-18.jpg",
        "/img/Album/LoveStory/Kristina & Andre/photo_4_2023-09-19_12-15-18.jpg",
        "/img/Album/LoveStory/Kristina & Andre/photo_7_2023-09-19_12-15-18.jpg",
        "/img/Album/LoveStory/Kristina & Andre/photo_13_2023-09-19_12-15-18.jpg",
        "/img/Album/LoveStory/Kristina & Andre/photo_14_2023-09-19_12-15-18.jpg",
        "/img/Album/LoveStory/Kristina & Andre/SWIP.jpg",
      ],
    },
    {
      id: "3",
      category: "wedding",
      title: "Kristina & Andre",
      mainImg: "img/Album/Wedding/Kristina & Andre/photo_4_2023-09-19_12-13-10.jpg",
      img: [
        "img/Album/Wedding/Kristina & Andre/SWIP.jpg",
        "img/Album/Wedding/Kristina & Andre/photo_4_2023-09-19_12-13-10.jpg",
        "img/Album/Wedding/Kristina & Andre/photo_2_2023-09-19_12-13-10.jpg",
        "img/Album/Wedding/Kristina & Andre/photo_6_2023-09-19_12-13-10.jpg",
        "img/Album/Wedding/Kristina & Andre/SWIP2.jpg",
        "img/Album/Wedding/Kristina & Andre/photo_7_2023-09-19_12-13-10.jpg",
        "img/Album/Wedding/Kristina & Andre/photo_9_2023-09-19_12-13-10.jpg",
        "img/Album/Wedding/Kristina & Andre/photo_10_2023-09-19_12-13-10.jpg",
        "img/Album/Wedding/Kristina & Andre/Wedding.jpg",
      ],
    },
  ],
  portfolioTittleImg: '/img/workStyle/portfolio.jpg'
};

export default data;
